# Database Configuration
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m

database.concurrent-write-permits=15
database.concurrent-read-permits=5

# Kafka
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.group-id=statify-synchronizer-connected-group
spring.kafka.admin.auto-create-topics=true
spring.kafka.listener.ack-mode=manual_immediate

# Spotify
spring.security.oauth2.client.registration.spotify.client-id=${SPOTIFY_CLIENT_ID}
spring.security.oauth2.client.registration.spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
spotify.api.base-url=${SPOTIFY_API_URL}
spotify.auth.base-url=${SPOTIFY_AUTH_URL}
spotify.timeout.seconds=${SPOTIFY_TIMEOUT_SECONDS}

# Actuator
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.access=unrestricted

# Tomcat
server.tomcat.threads.max=2
server.tomcat.accept-count=1

# Cache Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}

# Resilience4j
resilience4j.circuitbreaker.instances.spotifyCircuitBreaker.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.spotifyCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.spotifyCircuitBreaker.failure-rate-threshold=70
resilience4j.circuitbreaker.instances.spotifyCircuitBreaker.wait-duration-in-open-state=20s
resilience4j.circuitbreaker.instances.spotifyCircuitBreaker.permitted-number-of-calls-in-half-open-state=5