extend type Query {

    topAlbumsByPopularity(
        page: Int! @Range(min: 0)
        size: Int = 25 @Range(min: 1, max: 50)
        year: Int @Range(min: 1900, max: 2100)
        albumType: AlbumType = ALBUM
    ): [AlbumPreview!]!

    album(
        id: ID! @NotBlank
    ): AlbumDTO!

    albumTracks(
        id: ID! @NotBlank
    ): [TrackSimple!]!

    searchAlbums(
        query: String! @NotBlank @Size(min: 1, max: 100)
        page: Int! @Range(min: 0)
        size: Int = 10 @Range(min: 1, max: 20)
    ): [AlbumSimple!]!

    albumsByYear(
        year: Int! @Range(min: 1900, max: 2100)
    ): [AlbumSimple!]!

}

enum AlbumType {
    ALBUM
    SINGLE
    COMPILATION
}

type AlbumPreview {
    id: ID!
    name: String!
    artists: [ArtistSimple!]!
    covers: [Image!]!
}

type AlbumSimple {
    id: ID!
    name: String!
    albumType: AlbumType!
    totalTracks: Int!
    popularity: Int
    releaseDate: String!
}

type AlbumDTO {
    id: ID!
    name: String!
    albumType: AlbumType!
    totalTracks: Int!
    popularity: Int
    releaseDate: String!
    label: String
}