extend type Query {

    getMyFavoriteTracks(
        size: Int = 20, @Range(min: 1, max: 100)
        offset: Int = 0, @Range(min: 0)
    ): FavTrackConnection!

    getMyFavoriteAlbums(
        size: Int = 10, @Range(min: 1, max: 20)
        after: ID
    ): FavAlbumConnection!

}

type FavTrack {
    id: ID!
    durationMs: Int!
    explicit: Boolean!
    name: String!
    addedAt: String!
    artists: [ArtistSimple!]!
    covers: [Image!]!
    album: FavTrackAlbum!
}

type FavTrackAlbum {
    id: ID!
    name: String!
}

type FavAlbum {
    id: ID!
    albumType: String!
    totalTracks: Int!
    name: String!
    label: String
    popularity: Int
    releaseDate: String!
    addedAt: String!
}

type FavTrackConnection {
    items: [FavTrack!]!
    totalCount: Int
    hasMore: Boolean!
}

type FavAlbumConnection {
    edges: [FavAlbumEdge!]!
    pageInfo: PageInfo!
}

type FavAlbumEdge {
    node: FavAlbum!
    cursor: ID!
}