extend type Query {

    topArtistsByPopularity(
        page: Int! @Range(min: 0)
        size: Int = 50 @Range(min: 1, max: 100)
    ): [ArtistPreview!]!

    topArtistsByFollowers(
        page: Int! @Range(min: 0)
        size: Int = 50 @Range(min: 1, max: 100)
    ): [ArtistSimple!]!

    artist(
        id: ID! @NotBlank
    ): ArtistDTO!

    artistAlbums(
        id: ID! @NotBlank
    ): [AlbumSimple!]!

    artistTopTracks(
        id: ID! @NotBlank
    ): [TrackSimple!]!

}

type ArtistPreview {
    id: ID!
    name: String!
    images: [Image!]!
}

type ArtistSimple {
    id: ID!
    name: String!
    popularity: Int
    followersTotal: Int
}

type ArtistDTO {
    id: ID!
    name: String!
    popularity: Int
    followersTotal: Int
    topTracks: [TrackSimple!]!
    albums: [AlbumSimple!]!
}